# Generated by Django 3.2.3 on 2021-05-31 05:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('target', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
